---
apiVersion: batch/v1
kind: Job
metadata:
  name: gateway-cleanup
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      serviceAccountName: gateway-cleanup
      restartPolicy: Never
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Deleting gateways..."

              kubectl -n {{ .Release.Namespace }} delete gateways.gateway.networking.k8s.io eg-gw
