---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Release.Name }}-gateway-cleanup'
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Release.Name }}-gateway-cleanup'
  annotations:
    "helm.sh/hook": pre-delete
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
      - gatewayclasses
    verbs:
      - get
      - list
      - delete
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ .Release.Name }}-gateway-cleanup'
  annotations:
    "helm.sh/hook": pre-delete
subjects:
  - kind: ServiceAccount
    name: '{{ .Release.Name }}-gateway-cleanup'
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: '{{ .Release.Name }}-gateway-cleanup'
  apiGroup: rbac.authorization.k8s.io
