---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karpenter.fullname" . }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  revisionHistoryLimit: {{ .Values.controller.revisionHistoryLimit }}
  {{- with .Values.controller.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "karpenter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "karpenter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "karpenter.serviceAccountName" . }}
      {{- with .Values.controller.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: karpenter
          image: {{ include "karpenter.fullimage" . }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          env:
            - name: HEALTH_PROBE_PORT
              value: "{{ .Values.controller.healthProbe.port }}"
            - name: CLUSTER_ID
              value: {{ include "karpenter.controller.settings.clusterID" . }}
            {{- with .Values.logLevel }}
            - name: LOG_LEVEL
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.logOutputPaths }}
            - name: LOG_OUTPUT_PATHS
              value: "{{ join "," . }}"
            {{- end }}
            {{- with .Values.logErrorOutputPaths }}
            - name: LOG_ERROR_OUTPUT_PATHS
              value: "{{ join "," . }}"
            {{- end }}
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEADER_ELECTION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: karpenter
                  divisor: "0"
                  resource: limits.memory
            - name: FEATURE_GATES
              value: "SpotToSpotConsolidation={{ .Values.controller.featureGates.spotToSpotConsolidation }},NodeRepair={{ .Values.controller.featureGates.nodeRepair }}"
            {{- with .Values.controller.settings.batchMaxDuration }}
            - name: BATCH_MAX_DURATION
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.controller.settings.batchIdleDuration }}
            - name: BATCH_IDLE_DURATION
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.controller.settings.vmMemoryOverheadPercent }}
            - name: VM_MEMORY_OVERHEAD_PERCENT
              value: "{{ . }}"
            {{- end }}
            - name: METRICS_PORT
              value: "{{ .Values.controller.metrics.port }}"
            - name: KARPENTER_SERVICE
              value: {{ include "karpenter.fullname" . }}
            {{- with .Values.controller.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.controller.healthProbe.port }}
              protocol: TCP
            - name: http-metrics
              containerPort: {{ .Values.controller.metrics.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 30
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 30
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.credentials.enabled }}
            - mountPath: "/etc/config"
              readOnly: true
              name: cloud-config-volume
          {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.credentials.enabled }}
      volumes:
        - name: cloud-config-volume
          secret:
            defaultMode: 420
            secretName: {{ .Values.credentials.secretName }}
      {{- end }}
